# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

    paths: 
    - 'freeze.py' 
    - 'lint.py'
    - 'qrcodegenerator_test.py'
 
jobs: 
  build: 

    runs-on: ubuntu-latest 

    steps: 
    - uses: actions/checkout@v2 
    - name: Set up Python 3.8 
      uses: actions/setup-python@v2 
      with: 
        python-version: 3.8 
    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip 
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with pylint 
      run: |
        python lint.py
    - name: Run pytest suite 
      run: |
        pytest qrcodegenerator_test.py 

  deploy: 
    needs: build 
    name: Upload to Amazon S3 
    runs-on: ubuntu-latest 

    steps: 

    - name: Checkout 
      uses: actions/checkout@v2 
    - name: Configure AWS credentials 
      uses: aws-actions/configure-aws-credentials@v1 
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
        aws-region: us-east-1 
    - name: Copy our python module to our S3 bucket with the AWS CLI 
      run: |
        python -m pip install -r requirements.txt
        python freeze.py
        aws s3 sync build/ s3://${{ secrets.BUCKET_NAME }}

